name: 'supply_chain_hub'
version: '1.0.0'
config-version: 2

# Profile to load from profiles.yml
profile: 'supply_chain_hub'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  supply_chain_hub:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
    marts:
      +materialized: table
      +schema: analytics
      dimensions:
        +materialized: table
      facts:
        +materialized: table
      scorecards:
        +materialized: table

snapshots:
  supply_chain_hub:
    +target_schema: snapshots
