-- Staging model for FactPurchaseOrder
select
    cast(POLineKey as int64) as po_line_key,
    trim(cast(PurchaseOrderID as string)) as purchase_order_id,
    cast(POLineNumber as int64) as po_line_number,
    cast(POCreationDate as date) as po_creation_date,
    cast(PromisedDeliveryDate as date) as promised_delivery_date,
    cast(ActualDockReceiptDate as date) as actual_dock_receipt_date,
    cast(POCreationDateKey as int64) as po_creation_date_key,
    cast(PromisedDeliveryDateKey as int64) as promised_delivery_date_key,
    cast(ActualDockReceiptDateKey as int64) as actual_dock_receipt_date_key,
    cast(SupplierKey as int64) as supplier_key,
    trim(cast(SupplierCode as string)) as supplier_code,
    cast(ProductKey as int64) as product_key,
    trim(cast(ProductSKU as string)) as product_sku,
    cast(ReceivingWarehouseKey as int64) as receiving_warehouse_key,
    trim(cast(WarehouseCode as string)) as warehouse_code,
    cast(BuyerEmployeeKey as int64) as buyer_employee_key,
    cast(OrderedQuantity as int64) as ordered_quantity,
    cast(ReceivedQuantity as int64) as received_quantity,
    cast(RejectedQuantity as int64) as rejected_quantity,
    round(cast(UnitPurchasePrice as numeric), 2) as unit_purchase_price,
    round(cast(ExtendedPOAmount as numeric), 2) as extended_po_amount,
    cast(PromisedLeadTimeDays as int64) as promised_lead_time_days,
    cast(ActualLeadTimeDays as int64) as actual_lead_time_days,
    cast(LeadTimeVarianceDays as int64) as lead_time_variance_days,
    cast(IsDeliveredOnTimeFlag as int64) as is_delivered_on_time_flag,
    cast(IsDeliveredInFullFlag as int64) as is_delivered_in_full_flag,
    cast(IsSupplierOTIFFlag as int64) as is_supplier_otif_flag,
    trim(cast(POStatus as string)) as po_status
from {{ source('raw_supply_chain', 'raw_fact_purchase_order') }}
