-- Staging model for DimDate
select
    cast(DateKey as int64) as date_key,
    cast(FullDate as date) as full_date,
    cast(DayOfWeek as int64) as day_of_week,
    trim(cast(DayName as string)) as day_name,
    cast(DayOfMonth as int64) as day_of_month,
    cast(DayOfYear as int64) as day_of_year,
    cast(WeekOfYear as int64) as week_of_year,
    cast(MonthNumber as int64) as month_number,
    trim(cast(MonthName as string)) as month_name,
    trim(cast(MonthYear as string)) as month_year,
    cast(QuarterNumber as int64) as quarter_number,
    trim(cast(QuarterName as string)) as quarter_name,
    cast(YearNumber as int64) as year_number,
    cast(FiscalMonthNumber as int64) as fiscal_month_number,
    trim(cast(FiscalQuarter as string)) as fiscal_quarter,
    cast(FiscalYear as int64) as fiscal_year,
    cast(IsWeekday as boolean) as is_weekday,
    cast(IsHoliday as boolean) as is_holiday,
    trim(cast(SeasonalityPeriod as string)) as seasonality_period
from {{ source('raw_supply_chain', 'raw_dim_date') }}
